### ISSUE TITLE
Separation of Concerns

### ISSUE THREAD

**Issue by mehradsadeghi** [imanghafoori1/eloquent-history#3]
Hi Iman,
Hope you doing well.

Take a look at below method
https://github.com/imanghafoori1/eloquent-history/blob/200782d6f8dcbff80d21751e7f979654a55b7dd6/src/HistoryTracker.php#L104-L114

I think somehow the HTTP layer should become separated from here. This class feels like it should be consist of database related operations only, Also it makes writing tests more difficult.

Also is the reason you haven't used eloquent relations and syntax structure, To get higher performance ?

I guess GitHub issues might not be the proper place to discuss ideas and suggestions. It's ok with me if you prefer somewhere else.

**Comment by imanghafoori1** [comment]
what you say is correct, but for a small project does not matter.
You can make a PR to enhance it.

**Comment by mehradsadeghi** [comment]
> what you say is correct, but for a small project does not matter.
> You can make a PR to enhance it.

@imanghafoori1 
Not any good ideas comes to my mind that doesn't make layers more complicated and get the HTTP layer out of here.
:thinking: :thinking: :thinking: :thinking: :thinking:

**Comment by imanghafoori1** [comment]
I think the current state is fine for now.
