### ISSUE TITLE
Duplicated Trackings

### ISSUE THREAD

**Issue by mehradsadeghi** [imanghafoori1/eloquent-history#5]
I've noticed that if we call track on a model more than once, It'll track repeatedly that model events.
For example something like this:
```php
HistoryTracker::track(User::class);
HistoryTracker::track(User::class);
```
Doubles the columns being recorded.

Is this behaviour correct ?

**Comment by imanghafoori1** [comment]
User should not do that, it is their mistake not us.
But we can also help by ignoring or throwing an error.
